version: '3'

services:
  banking.api:
    image: data-warehouse/banking.api:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./src/Services/Banking/Dockerfile
    environment:
      ConnectionStrings:Default: Server=postgres;Database=baking;User ID=postgres;Password=admin123;    
    ports:
      - "5000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: admin123

